script_name("FTO ingame Handbook v1.0")
script_author("Oliver Blue")

function main()
	while not isSampAvailable() do wait(50) end
	sampAddChatMessage("{FFFF00}--------------  FTO ingame Handbook v1.0 active  -------------- {FFFFFF}/fto for more information.",-1)
	while true do wait(10) end
end

	
sampRegisterChatCommand("fto", function(params)
	if string.len(params) == 0 then
		lua_thread.create(function()
				sampAddChatMessage("{FFFF00}-------------- TRAINING PROCEDURES --------------",-1)
				sampAddChatMessage("/fto it: interview (/[fto 1] for IC questions, [/fto 2] for scenario-based questions and [/fto 3] for OOC Questions)",-1)
				sampAddChatMessage("/fto tt: Theory Training",-1)
				sampAddChatMessage("/fto pt: Practial Training",-1)
				sampAddChatMessage("/fto fr: First Ridealong",-1)
				sampAddChatMessage("/fto sr: Second Ridealong ([/fto 4] for turf rule Questions, [/fto 5] for Laws and Felonies Questions, [/fto 6] for Force Matrix Questions)",-1)
				sampAddChatMessage("this is in the works, it doesn't have everything updated right now.",-1)
				sampAddChatMessage("{FFFF00}----------------------------------------------------------------",-1)
			end)
	elseif string.match(params, "it") then
		lua_thread.create(function()
				sampAddChatMessage("{FFFF00}-------------- Interview Procedure --------------",-1)
				sampAddChatMessage("Ensure candidate is pending interview and is connected to lobby vc",-1)
				sampAddChatMessage("Greet him ICly and ask him IC questions, then scenario based questions",-1)
				sampAddChatMessage("Once done with the IC part, ask the server rules and roleplay with them",-1)
				sampAddChatMessage("Evaluate their skills and knowledge and make a decision based on it",-1)
				sampAddChatMessage("Update their application according to your decision and make a training file and train if they passed",-1)
				sampAddChatMessage("Use [/fto 1] for IC questions, [/fto 2] for scenario questions and [/fto 3] for OOC questions",-1)
				sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
			end)
		elseif string.match(params, "1") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}-------------- Interview IC questions --------------",-1)
			sampAddChatMessage("Q1: What made you interested in joining the Department?",-1)
			sampAddChatMessage("{add8e6}A1: It can be anything, focus on their English and evaluate whether they can properly type English in-game.",-1)
			sampAddChatMessage("Q2: Do you have any experience which might prove helpful to us as a department?",-1)
			sampAddChatMessage("{add8e6}A2: They must have any skills in which beneficial for the daily basis of an officer such as able physical...",-1)
			sampAddChatMessage("{add8e6}strength, marksmanship, or the ability to operate boats/aircraft",-1)
			sampAddChatMessage("Q3: Where do you see your LEO career in 6 months?",-1)
			sampAddChatMessage("{add8e6}A3: Any answer is acceptable.",-1)
			sampAddChatMessage("Q4: Do you prefer to work as a team or do you prefer to work individually and state a reason behind your answer?",-1)
			sampAddChatMessage("{add8e6}A4: Any answer is acceptable as long as he backs his option properly",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
			end)
	elseif string.match(params, "2") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}-------------- Scenario-Based questions --------------",-1)
			sampAddChatMessage("Q1: Someone comes up to you and insults you. What are you going to do?",-1) 
			sampAddChatMessage("{add8e6}A2: Ignoring them is acceptable. Diffusing the situation is also good. Calming them down",-1)
			sampAddChatMessage("Q2: There are 3 backup requests; one of them is for a non-compliant trucker, one of them is about an active pursuit (10-80)",-1)
			sampAddChatMessage(" and one of them is for an Officer down. What are you going to respond to first and why?",-1)
			sampAddChatMessage("{add8e6}A2: They should respond to the last request as it is a life-threatening situation.",-1)
			sampAddChatMessage("Q3: You are in a situation where you can either save yourself or a civilian. What are you going to do?",-1)
			sampAddChatMessage("{add8e6}A3: They should prioritize the civilian's life, PD members are to serve and protect, and sacrifice.",-1)
			sampAddChatMessage("Q4: You were patrolling and you saw a civilian shooting his weapon at a wall, what are your actions?",-1)
			sampAddChatMessage("{add8e6}A4: You can withdraw your firearm and aim, telling them to drop it. You can also calmly tell the person to stop",-1)
			sampAddChatMessage("{add8e6}without escalating the situation.",-1)
			sampAddChatMessage("Q5: A gang member has a hostage in his car and you are following him, when would you shoot the vehicle?",-1)
			sampAddChatMessage("{add8e6}A5: They obviously shouldn't, they will be endangering the hostage's life if they do so.",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
			end)
	elseif string.match(params, "3") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}-------------- OOC Questions --------------",-1)
			sampAddChatMessage("Ask the full form, definition and 2 examples related to the faction of each rule listed below",-1)
			sampAddChatMessage("DM, RK, MG, SK, LTA, TRV",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
		elseif string.match(params, "tt") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- Theory Training -------------------------",-1)
			sampAddChatMessage("Once you're starting the training, ask the candidate to provide a screenshot of their /stats and post it on their Training File",-1)
			sampAddChatMessage("Give a tour of the Department to the cadet and `tell them how the locker works and how reassignments work",-1)
			sampAddChatMessage("how divisions work and inform them of the vehicle policy and the commonly used radio codes",-1)
			sampAddChatMessage("Inform the cadet of the department policies including the 2 week policy for cadets and how he should act",-1)
			sampAddChatMessage("Tell him that he's supposed to be on dispatch at all times and cannot go off-duty as a cadet",-1)
			sampAddChatMessage("Send him the links from the from the spoiler in the Handbook and tell him about the faction rules, Force Matrix....",-1)
			sampAddChatMessage("..-Turf rules and how to conduct MPS duties when a 10-16 isn't available",-1)
			sampAddChatMessage("Make sure that the cadet reads the sent links themselves and you don't read it to them, you should only tell them the important ones",-1)
			sampAddChatMessage("Let the cadet know that he can take his Practical Training in 24 hours and you ensure that you've posted his /stats on the training file",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	elseif string.match(params, "pt") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- Practical Training -------------------------",-1)
			sampAddChatMessage("Ensure that the cadet took his Theory more than 24 hours, take him to LV with 2 cruisers and start the Practical Training",-1)
			sampAddChatMessage("Show them how to conduct a 10-26, a 10-26a, a proper 10-80 with updating and Arrest Procedure",-1)
			sampAddChatMessage("Once you show them how to do a 10-26, let them do one on you, point out any mistakes they do so they know how to properly do them",-1)
			sampAddChatMessage("Show them how to do a 10-26a and ensure that they know how to park the cruiser and how to arrest the suspect",-1)
			sampAddChatMessage("During the 10-80, show them proper updating skills and tell them when the suspect's VFM level changes throughout the pursuit",-1)
			sampAddChatMessage("Also inform them that if they should download the street names map and a compass to make it easier",-1)
			sampAddChatMessage("Be cuffed for the arresting procedure so it's more hands-on. Tell them about the charge.lua mod and how it can save them from being prisoned.",-1)
			sampAddChatMessage("While conducting the arrest procedure, ask the cadet which charges do you get to get a sense of his knowledge of charges and which stack",-1)
			sampAddChatMessage("Let the cadet know that he can take his First Ridealong in 24 hours and ensure that you have updated their training file",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	elseif string.match(params, "fr") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- First Ridealong -------------------------",-1)
			sampAddChatMessage("Ensure that the cadet has taken their Practical Training more than 24 hours ago and was set pending ridealongs by a supervisor+",-1)
			sampAddChatMessage("This ia a short ridealong as it only consists of a short 10-80 test and come field testing",-1)
			sampAddChatMessage("Take 2 cruisers and the cadet to LV and ask them to chase you, evaluate their updating and let them know of their mistakes if there are any",-1)
			sampAddChatMessage("Now let the cadet drive the cruiser and patrol as he would do as an officer. Evaluate their responses to situations",-1)
			sampAddChatMessage("Let the cadet conduct a 10-26 and note down his mistakes, don't rush him or give him any orders, the purpose of this is to see how they do",-1)
			sampAddChatMessage("If you find a suspect who is to be arrested, let the cadet arrest him but you make sure that he doesn't break any server rules while doing do",-1)
			sampAddChatMessage("Use your discretion as to which situations you should use to evaluate the cadet,  This will show you whether he can apply the rules...",-1)
			sampAddChatMessage("..-he has learned in both trainings.",-1)
			sampAddChatMessage("Tell the cadet that he can take his Second ridealong in 12 hours and update their training file",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	elseif string.match(params, "sr") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- Second Ridealong -------------------------",-1)
			sampAddChatMessage("Ensure that the first ridealong was done more than 12 hours ago.",-1)
			sampAddChatMessage("Once again, let the cadet take lead in the situations for atleast 10-15 minutes.",-1)
			sampAddChatMessage("Evaluate his reactions and tell him how he can improve them once the ridealong ends.",-1)
			sampAddChatMessage("Ask the Cadet about the following faction rules: RK, FT, Backup and RK rules for LEOs, Charge Stacking Faction Doors.",-1)
			sampAddChatMessage("Ask the cadet about Force Matrix, specific questions can be found in [/fto srfmques]. He should get atleast 3 questions right out of the 5",-1)
			sampAddChatMessage("Ask the Cadet about turf rules, specific questions can be found in [/fto srtuques]. He should get atleast 4 questions right out of the 6",-1)
			sampAddChatMessage("in the end, ask him questions about laws, specific questions can be found in [/fto srlques]. he should get atleast 4 questions out of the 6",-1)
			sampAddChatMessage("Let him know that he can take his Exam in 48 hours and update their training file.",-1)
			sampAddChatMessage("/fto 4 for turf rule Questions, /fto 5 for Laws and Felonies Questions, /fto 6 for Force Matrix Questions",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	elseif string.match(params, "4") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- Turf Rule Questions -------------------------",-1)
			sampAddChatMessage("Q; Can you deploy cades and spikes in a turf? A:{add8e6}No{FFFFFF}",-1)
			sampAddChatMessage("Q: Can you attend a turf as a LEO without intention to capture? A:{add8e6} Yes they can{FFFFFF}",-1)
			sampAddChatMessage("Q: Can you use a beanbag or tazer on someone inside a turf? A:{add8e6}No{FFFFFF}",-1)
			sampAddChatMessage("Q: Can you as an LEO attend a turf with a gang / civilian skin? A:{add8e6}No{FFFFFF}",-1)
			sampAddChatMessage("Q: Are you allowed to attend a point? If not, why? A:{add8e6}No, points are only for gangs.{FFFFFF}",-1)
			sampAddChatMessage("Are you allowed to revenge kill in at a turf? If yes, why? A:{add8e6}Yes as RK is allowed in turfs{FFFFFF}",-1)
			sampAddChatMessage("He should get atleast 3 of these right",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	elseif string.match(params, "5") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- Laws and Felonies Questions -------------------------",-1)
			sampAddChatMessage("Q: Can you give someone Failure to Provide ID and Evading together? A: {add8e6}Yes{FFFFFF}",-1)
			sampAddChatMessage("Q: Can you give someone Failure to Comply and Failure to Provide ID together? A: {add8e6}No{FFFFFF}",-1)
			sampAddChatMessage("Q: Can you give someone Possession of Illegal Narcotics and Distribution of Illegal Narcotics together? A: {add8e6}No{FFFFFF}",-1)
			sampAddChatMessage("Q: Can you give someone Discharge of a Firearm in Public and Attempted Murder together? A: {add8e6}No{FFFFFF}",-1)
			sampAddChatMessage("Q: What's the charge for taking a gun out in public? A:{add8e6} Brandishing a Firearm in Public{FFFFFF}",-1)
			sampAddChatMessage("Q: What's the charge for someone that's trucking illegal goods? A:{add8e6} Transportation of Illegal Goods{FFFFFF}",-1)	
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	elseif string.match(params, "6") then
		lua_thread.create(function()
			sampAddChatMessage("{FFFF00}---------------------------- Force Matrix Questions -------------------------",-1)
			sampAddChatMessage("Q1: What is the force matrix level of a person who is being verbally aggressive towards you?",-1)
			sampAddChatMessage("A1: {add8e6}Force Matrix level 1",-1)
			sampAddChatMessage("Q2:  What is the force matrix level of a person who is aiming their firearm at a civilian?",-1)
			sampAddChatMessage("A2: {add8e6}Force Matrix level 4",-1)
			sampAddChatMessage("Q3: What is the force matrix level of a person who has committed a crime?",-1)
			sampAddChatMessage("A3: {add8e6}Force Matrix level 3",-1)
			sampAddChatMessage("Q4: When is a person considered as FM5?",-1)
			sampAddChatMessage("A4: {add8e6} When a suspect aims their firearm at a Law Enforcement Officer, When a person is most wanted, when.... ",-1)
			sampAddChatMessage("{add8e6}..-the person is causing threat to Human Life, the suspect has escaped Castile Island or have entered the castile area",-1)
			sampAddChatMessage("Q5: What is the force matrix level of a person who might have committed a crime?",-1)
			sampAddChatMessage("A5: {add8e6}Force Matrix level 2",-1)
			sampAddChatMessage("{FFFF00}----------------------------------------------------------------------",-1)
		end)
	else
		sampAddChatMessage("USAGE: /fto [procedure] or /fto for a list of commands.",-1)
	end
end)

